services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      TZ: "Europe/Stockholm"
    ports:
      - '10080:80'
      - '10081:81'
      - '10443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
